exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

title: "Civic Labs"
subtitle: "Not Just Code. The Right Code. Medical and Financial Software Consulting with Haskell and Coq."
url: "https://www.civiclabs.com"
baseurl: ""
cover: "/assets/img/feature-bg.jpg"
logo: "/assets/img/logo-small.png"

markdown: kramdown

ga_tracking_id: "UA-80053910-1"

descriptions:
  - cat: haskell
    desc: "Purely functional programming language"

  - cat: coq
    desc: "Interactive theorem prover and programming language"

gems:
  - listen
  - jekyll-assets
  - rouge
  - pygments.rb
  - jekyll-paginate
  - jekyll-watch
  - kramdown
  - rouge
  - jekyll-sitemap
  - liquid_reading_time
  - jekyll-seo-tag
  - jekyll-seo
  - jekyll-assets
  - jekyll/scholar

paginate_path: "/blog/page:num/"

assets:
  prefix: "/assets"
  sources:
    - _assets
  autowrite: true
  cache: .asset-cache
  cache_type: filesystem
  skip_baseurl_with_cdn: true
  skip_prefix_with_cdn: true
  assets:
    - "*.png"
    - "*.jpg"
    - "*.css"
    - "*.ttf"
    - "*.woff"
  features:
    integrity: false
    automatic_img_size: true
    automatic_img_alt : true
