exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

title: "Civic Labs"
subtitle: "Not Just Code. The Right Code."
url: "https://www.civiclabs.com"
baseurl: ""
cover: "/assets/cover.png"
logo: "/assets/logo.png"

markdown: kramdown

ga_tracking_id: "UA-80053910-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."

gems:
  - listen
  - jekyll-assets
  - rouge
  - pygments.rb
  - jekyll-paginate
  - jekyll-watch
  - kramdown
  - rouge
  - jekyll-sitemap
  - liquid_reading_time
  - jekyll-seo-tag
  - jekyll-seo
  - jekyll-assets
  - jekyll/scholar

paginate_path: "/blog/page:num/"

assets:
  compress:
    css: true
    js: true

  autowrite: true
  cache: false
  skip_baseurl_with_cdn: true
  skip_prefix_with_cdn: true
  digest: true

  assets:
    - "*.png"
    - "bundle.css"

  sources:
    - css
    - img
    - js
    - css
    - fonts

  features:
    integrity: false
    automatic_img_size: true
    automatic_img_alt : true
